---
- name: Odoo | Custom addons | Create SSH dir if not exist
  become: yes
  file:
    state: directory
    path: "{{ item.1.ssh_private_key_dir | default(default_ssh_private_key_dir) }}"
    force: False
    owner: "{{ item.0.odoo_user }}"
    group: "{{ item.0.odoo_user }}"
  with_subelements:
    - "{{ odoo_instances }}"
    - odoo_custom_addons
    - flags:
      skip_missing: True
  when: "{{ item.1.deploy_ssh_private_key | default('false') }}"

- name: Odoo | Custom addons | Deploy SSH key  (Git)
  become: yes
  copy:
    src: "{{ item.1.ssh_private_key_file }}"
    backup: True
    dest: "{{ item.1.ssh_private_key_dest | default(default_ssh_private_key_dest) }}"
    force: True
    mode: 0600
    owner: "{{ item.0.odoo_user }}"
    group: "{{ item.0.odoo_user }}"
  with_subelements:
    - "{{ odoo_instances }}"
    - odoo_custom_addons
    - flags:
      skip_missing: True
  when: "{{ item.1.deploy_ssh_private_key | default('false') }}"

- name: Odoo | Custom addons | Clone submodules repository (Git)
  become: yes
  become_user: "{{ item.0.odoo_user }}"
  git:
    repo: "{{ item.1.addon_url }}"
    dest: "{{ item.1.addon_dest | default(default_addon_dest) }}"
    version: "{{ item.1.addon_branch  | default('master') | string }}"
    update: False
    accept_hostkey: "{{ item.1.accept_hostkey | default('True') }}"
    force: "{{ item.1.force_rewrite | default('False') }}"
    key_file: "{{ item.1.key_file | default(default_ssh_private_key_dest) }}"
    depth: "{{ item.1.repo_depth  | default(omit) }}"
  with_subelements:
    - "{{ odoo_instances }}"
    - odoo_custom_addons
    - flags:
      skip_missing: True
  notify: Odoo | Handlers | Restart Odoo

- name: Odoo | Custom addons | Update submodules repository (Git)
  become: yes
  become_user: "{{ item.0.odoo_user }}"
  git:
    repo: "{{ item.1.addon_url }}"
    dest: "{{ item.1.addon_dest | default(default_addon_dest) }}"
    version: "{{ item.1.addon_branch  | default('master') | string }}"
    update: True
    accept_hostkey: "{{ item.1.accept_hostkey | default('True') }}"
    force: "{{ item.1.force_rewrite | default('False') }}"
    key_file: "{{ item.1.key_file | default(default_ssh_private_key_dest) }}"
    depth: "{{ item.1.repo_depth  | default(omit) }}"
  when: ({{ item.1.update_addon }} is defined)
        and ({{ item.1.update_addon }} == True)
  with_subelements:
    - "{{ odoo_instances }}"
    - odoo_custom_addons
    - flags:
      skip_missing: True
  notify: Odoo | Handlers | Restart Odoo
