---

- name: Odoo | wkhtmltox | Detect Debian architecture (i386 or amd64)
  set_fact: 
    odoo_debian_arch: "{{ '64' in ansible_architecture and 'amd64' or 'i386' }}"

- name: Odoo | wkhtmltox | Check current installed version
  command: dpkg-query -W -f='${Version}' wkhtmltox
  register: wkhtmltox_exist_version
  ignore_errors: yes

- name: Odoo | wkhtmltox | Download wkhtmltox
  get_url: 
    url: "{{ item }}"
    dest: "{{ odoo_wkhtmltox_dest }}"
  with_items: "{{ odoo_wkhtmltox_urls }}"
  ignore_errors: True
  when: odoo_wkhtmltox_version is defined 
        and odoo_wkhtmltox_version != False
        and wkhtmltox_exist_version.stdout != odoo_wkhtmltox_version

# Use to detect that the package was downloaded.
# We can not register the result of the previous task to check this as Ansible
# will flag it as failed as soon as one URL fails (even if the download has
# worked on a further URL)
- name: Odoo | wkhtmltox | Check wkhtmltox package
  stat: 
    path: "{{ odoo_wkhtmltox_dest }}"
  register: odoo_wkhtmltox_pkg

- name: Odoo | wkhtmltox | Install wkhtmltox dependencies
  apt:  
    pkg: "{{ item }}"
  with_items: "{{ odoo_wkhtmltox_depends }}"
  when: odoo_wkhtmltox_version is defined 
        and odoo_wkhtmltox_version != False 
        and odoo_wkhtmltox_pkg.stat.exists
        and wkhtmltox_exist_version.stdout != odoo_wkhtmltox_version

- name: Odoo | wkhtmltox | Install wkhtmltox
  apt:  
    deb: "{{ odoo_wkhtmltox_dest }}"
  when: odoo_wkhtmltox_version is defined 
        and odoo_wkhtmltox_version != False 
        and odoo_wkhtmltox_pkg.stat.exists
        and wkhtmltox_exist_version.stdout != odoo_wkhtmltox_version

- name: Odoo | wkhtmltox | Remove deb downloaded file from temp
  file: 
    path: "{{ odoo_wkhtmltox_dest }}"
    state: absent
  when: "{{ odoo_wkhtmltox_pkg.stat.exists }}"
